title: Sierra Rehm
logo: "images/logo.svg" # You can add own logo image.
description: Minimalistic Theme for Jekyll
baseurl: "" # The subpath of your site, e.g. /blog
url: "" # The base hostname & protocol for your site, e.g. http://example.com
# Author Settings
author:
  name: Sierra Rehm
  bio: Hi, my name is Sierra Rehm.

# Contact links
twitter: https://twitter.com/sierraspaige # Add your Twitter handle
instagram: https://www.instagram.com/sierrainfinity/?hl=en # Add your Instagram handle
email: sierraprehm@gmail.com # Add your Email address

# Hero Section
hero: true # To enable the section hero, use the value true. To turn off use the value false.
hero-title: Sierra Rehm # Add your hero title
hero-subtitle: Digital Journalist # Add your hero subtitle
hero-image: images/14.jpg # Add background image in section hero

# Footer
footer-image: images/14.jpg # Add background image in footer

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Google Analytics
google-analytics: "" # Add your identifier. For example UA-99631805-1.

# Newsletter
mailchimp: "" # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 4
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

#Publications
publication_page_dir:  publication
publication_page_layout: publication_page
publicaiton_permalink_style: pretty

sass:
  sass_dir: _sass
  style: compressed